builds:
  - binary: genie
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: genie
    homepage: "https://github.com/harshalranjhani/genie"
    repository:
      owner: harshalranjhani
      name: homebrew-harshalranjhani
    commit_author:
      name: gmorse81
      email: gmorse81@gmail.com

checksum:
  name_template: 'checksums.txt'