name: Trigger Remote Workflow on Release

on:
  release:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          repository: harshalranjhani/genie-web
          event-type: new-release-triggered
