name: Trigger Remote Workflow on Release

on:
  release:
    types: [created]
  push:
      tags:
        - "*"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Delay
        run: |
          echo "Waiting for 10 minutes..."
          sleep 600 # Sleep for 600 seconds or 10 minutes
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          repository: harshalranjhani/genie-web
          event-type: trigger-workflow-event
