name: Trigger Remote Workflow

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the workflow on

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          repository: harshalranjhani/genie-web
          event-type: trigger-workflow-event
